# Generated by Django 3.0.9 on 2020-08-29 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assetTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=299)),
                ('is_status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=299)),
                ('is_status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='nav_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('scheme_name', models.TextField(max_length=299)),
                ('isis_div_payout', models.CharField(max_length=299, null=True)),
                ('isis_div_reinvestment', models.CharField(max_length=299, null=True)),
                ('net_asset_value', models.TextField(max_length=299)),
                ('repurchase_price', models.TextField(max_length=299)),
                ('sale_price', models.TextField(max_length=299)),
                ('date_open_ended', models.TextField(max_length=299)),
            ],
        ),
        migrations.CreateModel(
            name='riskProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=299)),
                ('is_status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='schema_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amc', models.TextField(max_length=299)),
                ('code', models.IntegerField()),
                ('scheme_name', models.TextField(max_length=299)),
                ('scheme_type', models.TextField(max_length=299)),
                ('scheme_category', models.TextField(max_length=299)),
                ('scheme_nav_name', models.TextField(max_length=299)),
                ('scheme_minimum_amount', models.TextField(max_length=299)),
                ('launch_date', models.TextField(max_length=299)),
                ('closure_date', models.TextField(max_length=299)),
                ('isis_div_payout', models.CharField(max_length=299, null=True)),
                ('isis_div_reinvestment', models.CharField(max_length=299, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.TextField(max_length=299)),
                ('percent', models.IntegerField()),
                ('is_status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='timeHorizons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=300)),
                ('period_year', models.TextField(max_length=299)),
                ('description', models.TextField(max_length=299)),
                ('is_status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=299)),
                ('is_status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unovestAdmin.category')),
            ],
        ),
    ]
